### ISSUE TITLE
any way i could help?

### ISSUE THREAD

**Issue by Mustwey** [MrEmpy/Frosty#1]
im interested in this project, but couldn't find any info on how you would like to improve it or bugs that need to be fixed

**Comment by Mustwey** [comment]
How about considering a different approach for this rootkit? For example, you could improve this rootkit by integrating a ui. This ui could allow users to generate a standalone executable, containing only the specific features they require. For example, if a user's sole goal is to bypass AMSI, they could use this interface to create an executable focused exclusively on that functionality, without incorporating any unnecessary components. This approach would streamline the executable, making it more efficient and prolly lower the detection rate of it too.

**Comment by brosck** [comment]
Hi @Mustwey

I liked this idea of changing to Frosty Rootkit. I will mark your comment as an idea for the next versions of the project.

If you find a bug, you can report it here.

Regards,
\- MrEmpy
